version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn start

workflows:
  version: 2
  commit:
    jobs:
      - build
